print( math.sin( 0.0 ) )
print( math.cos( math.pi ) )
print( math.sqrt( 9.0 ) )
print( math.modf( 5.25 ) )


-- binary ops
function binops( a, b )
	local sa = tostring(a)
	local sb = tostring(b) 
	print( sa..'+'..sb..'='..tostring(a+b) )
	print( sa..'-'..sb..'='..tostring(a-b) )
	print( sa..'*'..sb..'='..tostring(a*b) )
	print( sa..'^'..sb..'='..tostring(a^b) )
	print( sa..'/'..sb..'=',pcall( function() return a / b end ) ) 
	print( sa..'%'..sb..'=',pcall( function() return a % b end ) )
	return '--' 
end
print( pcall( binops, 2, 0 ) )
print( pcall( binops, -2, 0 ) )
print( pcall( binops, 2.5, 0 ) )
print( pcall( binops, -2.5, 0 ) )
print( pcall( binops, 2, 1 ) )
print( pcall( binops, 5, 2 ) )
print( pcall( binops, -5, 2 ) )
print( pcall( binops, 16, -2 ) )
print( pcall( binops, -16, -2 ) )
print( pcall( binops, 256, .5 ) )
print( pcall( binops, 256, .25 ) )
print( pcall( binops, 256, .625 ) )
print( pcall( binops, 256, -.5 ) )
print( pcall( binops, 256, -.25 ) )
print( pcall( binops, 256, -.625 ) )
print( pcall( binops, -256, .5 ) )
print( pcall( binops, .5, 0 ) )
print( pcall( binops, .5, 1 ) )
print( pcall( binops, .5, 2 ) )
print( pcall( binops, .5, -1 ) )
print( pcall( binops, .5, -2 ) )
print( pcall( binops, 2.25, 0 ) )
print( pcall( binops, 2.25, 2 ) )
print( pcall( binops, 2.25, .5 ) )
print( pcall( binops, 2.25, 2.5 ) )


-- random tests
print( math.random(5,10) )
print( math.random(5,10) )
print( math.random(5,10) )
print( math.random(5,10) )
print( math.random() )
print( math.random() )
print( math.random() )
print( math.random() )
print( math.randomseed(20), math.random(), math.random(), math.random() )
print( math.randomseed(20), math.random() )
print( math.randomseed(20), math.random() )
print( math.randomseed(30), math.random() )
print( math.randomseed(30), math.random() )
print( math.random(30) )
print( math.random(30) )
print( math.random(30) )
print( math.random(30) )
print( math.random(-4,-2) )
print( math.random(-4,-2) )
print( math.random(-4,-2) )
print( math.random(-4,-2) )
print( math.random(-4,-2) )
